apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocalizer-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: geolocalizer-app
  template:
    metadata:
      labels:
        app: geolocalizer-app
    spec:
      containers:
      - name: geolocalizer-container
        image: alejandromoralbermejo/geolocalizer:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-credentials
        env:
        - name: DB_HOST
          value: "db"
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
